import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,existsSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {generateKeyPairSync,sign} from 'node:crypto';
import {evaluate,inspect,keyId,stable,match} from '../trust-gate.mjs';
const now=new Date('2026-09-25T10:00:00Z');
function setup(t) {
 const dir=mkdtempSync(join(tmpdir(),'jarvis-v4-gate-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));
 const git=(...args)=>{const r=spawnSync('git',args,{cwd:dir,encoding:'utf8'});assert.equal(r.status,0,r.stderr);return r.stdout.trim();};
 git('init','-q');git('config','user.email','fixture@example.invalid');git('config','user.name','Synthetic Fixture');
 const put=(p,s)=>{mkdirSync(join(dir,p,'..'),{recursive:true});writeFileSync(join(dir,p),s);};
 put('AGENTS.md','baseline');put('docs/ADR/0001-base.md','immutable');put('src/main.ts','baseline');
 git('add','.');git('commit','-qm','base');const base=git('rev-parse','HEAD');
 const keys=generateKeyPairSync('ed25519');const pem=keys.publicKey.export({type:'spki',format:'pem'});
 const policy={policyVersion:2,defaultClassification:'protected',requireEnrolledKeyForPromotion:true,bootstrapStatus:'owner_key_enrolled',operationalAllowedSuffixes:['.json','.md','.txt'],operationalModes:['100644'],repository:'fixture/jarvis',protectedPatterns:['AGENTS.md','tools/**','governance/**'],operationalExceptions:[],immutableExistingPatterns:['docs/ADR/[0-9]*'],immutableExceptions:[],trustedKeyIds:[keyId(pem)],maxApprovalSeconds:3600};
 const commit=()=>{git('add','.');git('commit','-qm','candidate');return git('rev-parse','HEAD');};
 const approve=head=>{const r=inspect(dir,base,head,policy);const payload={repository:policy.repository,base,head,diffDigest:r.diffDigest,purpose:'protected-change-promotion',keyId:keyId(pem),issuedAt:'2026-09-25T09:59:00Z',expiresAt:'2026-09-25T10:30:00Z'};return {format:'jarvis-governance-approval-v1',payload,signature:sign(null,Buffer.from(stable(payload)),keys.privateKey).toString('base64')};};
 const check=(head,envelope=null,changes={})=>evaluate({repo:dir,base,head,policy,envelope,publicKey:pem,now,...changes});
 return {dir,git,put,base,pem,policy,keys,commit,approve,check};
}
test('ordinary code now requires exact owner approval',t=>{const x=setup(t);x.put('src/main.ts','new');const h=x.commit();assert.equal(x.check(h).allowed,false);assert.equal(x.check(h,x.approve(h)).allowed,true);});
test('protected diff denied unsigned',t=>{const x=setup(t);x.put('AGENTS.md','weaken');assert.equal(x.check(x.commit()).allowed,false);});
test('exact owner signature admits protected diff',t=>{const x=setup(t);x.put('AGENTS.md','reviewed');const h=x.commit();assert.equal(x.check(h,x.approve(h)).allowed,true);});
test('changed head invalidates approval',t=>{const x=setup(t);x.put('AGENTS.md','reviewed');const h=x.commit(),e=x.approve(h);x.put('AGENTS.md','later');assert.equal(x.check(x.commit(),e).allowed,false);});
test('tampered envelope rejected',t=>{const x=setup(t);x.put('AGENTS.md','new');const h=x.commit(),e=x.approve(h);e.payload.expiresAt='2026-09-25T10:31:00Z';assert.equal(x.check(h,e).allowed,false);});
test('expired approval rejected',t=>{const x=setup(t);x.put('AGENTS.md','new');const h=x.commit();assert.equal(x.check(h,x.approve(h),{now:new Date('2026-09-25T11:00:00Z')}).allowed,false);});
test('unregistered key rejected',t=>{const x=setup(t);x.put('AGENTS.md','new');const h=x.commit(),e=x.approve(h);x.policy.trustedKeyIds=[];assert.equal(x.check(h,e).allowed,false);});
test('wrong signature rejected',t=>{const x=setup(t);x.put('AGENTS.md','new');const h=x.commit(),e=x.approve(h);e.signature=Buffer.alloc(64).toString('base64');assert.equal(x.check(h,e).allowed,false);});
test('immutable history denied even signed',t=>{const x=setup(t);x.put('docs/ADR/0001-base.md','rewrite');const h=x.commit();assert.equal(x.check(h,x.approve(h)).allowed,false);});
test('new history is an authorized append, not an unsigned policy change',t=>{const x=setup(t);x.put('docs/ADR/0002-new.md','new');const h=x.commit();assert.equal(x.check(h).allowed,false);assert.equal(x.check(h,x.approve(h)).allowed,true);});
test('candidate checker never executed',t=>{const x=setup(t);const marker=join(x.dir,'EXECUTED');x.put('tools/malicious.mjs',`require('fs').writeFileSync(${JSON.stringify(marker)},'yes')`);const h=x.commit();assert.equal(x.check(h).allowed,false);assert.equal(existsSync(marker),false);});
test('candidate trust policy cannot change supplied baseline',t=>{const x=setup(t);x.put('governance/TRUST_POLICY.json',JSON.stringify({protectedPatterns:[]}));x.put('AGENTS.md','weakened');assert.equal(x.check(x.commit()).allowed,false);});
test('same signature cannot promote another repository identity',t=>{const x=setup(t);x.put('AGENTS.md','new');const h=x.commit(),e=x.approve(h);x.policy.repository='other/project';assert.equal(x.check(h,e).allowed,false);});
test('full SHA required, branch name is not accepted',t=>{const x=setup(t);assert.throws(()=>x.check('HEAD'));});
test('glob boundaries and history prefixes',()=>{assert.equal(match('docs/ADR/[0-9]*','docs/ADR/0001-x.md'),true);assert.equal(match('docs/*.md','docs/nested/x.md'),false);assert.equal(match('tools/**','tools/a/b'),true);});
test('canonical payload refuses noninteger floats',()=>assert.throws(()=>stable({amount:1.3})));
test('invalid trusted verifier clock fails closed',t=>{const x=setup(t);x.put('AGENTS.md','reviewed');const h=x.commit();assert.equal(x.check(h,x.approve(h),{now:new Date('invalid')}).allowed,false);});
